apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-ca
  namespace: cert-manager
spec:
  secretName: yanivzl-tls
  commonName: yanivzl.com
  duration: 8760h # 365d
  renewBefore: 360h # 15d
  usages:
    - server auth
    - client auth
  isCA: true
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer