apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capitolis-devops-demo-web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/yanivzl/capitolis-demo-infra.git
    targetRevision: HEAD
    path: kubernetes/argocd/
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true